### ISSUE TITLE
Laravel not autoloading / registering Service provider

### ISSUE THREAD

**Issue by LTKort** [Kaishiyoku/laravel-recharts#9]
I needed to add in my controller:
`use Kaishiyoku\LaravelRecharts\LaravelRecharts; `

And in my app.php:
`Kaishiyoku\LaravelRecharts\LaravelRechartsServiceProvider::class,`

It should be usefull to add auto registering & add in the docs that you need to publish the assests

Maybe add something to your composer file;
`
"extra": {
        "laravel": {
            "providers": [
                "Kaishiyoku\\LaravelRecharts\\LaravelRechartsServiceProvider"
            ]
        }
    }
`

**Comment by Kaishiyoku** [comment]
Added; new release: [0.6.0](https://github.com/Kaishiyoku/laravel-recharts/releases/tag/0.6.0)


I also adjusted the docs.

Thank you very much for opening an issue :)
